Repository ccmbioinfo/stager, pull requests merged in 2020-11, with the labels that each got.

#125 Database schema changes
  flask/app/__init__.py
  flask/app/manage.py
  flask/app/models.py
  flask/app/routes.py
  flask/migrations/versions/00462e44baf0_updates_to_participant_table.py
  flask/migrations/versions/504637ea7e26_using_tables_for_dataset_types.py
  react/src/pages/participants/ParticipantTable.tsx
Labels: database

#140 Flask: family endpoints
  flask/app/__init__.py
  flask/app/families.py
Labels: backend

#141 Flask: add DELETE /api/analyses/:id
  flask/app/__init__.py
  flask/app/analyses.py
  flask/app/routes.py
Labels: backend

#142 Flask: add DELETE, PATCH, GET /api/families/:id
  flask/app/families.py
Labels: backend

#145 React: fix rendering failure when there are no datasets for a participant or tissue sample
  react/src/pages/participants/ParticipantTable.tsx
Labels: bug, frontend

#146 Flask: DELETE /api/participants/:id
  flask/app/__init__.py
  flask/app/manage.py
  flask/app/participants.py
  flask/app/routes.py
Labels: backend

#144 React: standardize UI and refactor frontend code
  react/src/App.tsx
  react/src/pages/AnalysisInfoDialog.tsx
  react/src/pages/Notification.tsx
  react/src/pages/NotificationPopover.tsx
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/analysis/CancelAnalysisDialog.tsx
  react/src/pages/analysis/SetAssigneeDialog.tsx
  react/src/pages/datasets/AnalysisRunnerDialog.tsx
  react/src/pages/datasets/DatasetInfoDialog.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/datasets/Datasets.tsx
  react/src/pages/datasets/DialogSections.tsx
  react/src/pages/participants/AnalysisTable.tsx
  react/src/pages/participants/DatasetAccordion.tsx
  react/src/pages/participants/DatasetTypes.tsx
  react/src/pages/participants/ParticipantDetailDialog.tsx
  react/src/pages/participants/ParticipantInfoDialog.tsx
  react/src/pages/participants/ParticipantTable.tsx
  react/src/pages/participants/SampleTable.tsx
  react/src/pages/utils.tsx
  react/src/pages/utils/components/AnalysisInfoDialog.tsx
  react/src/pages/utils/components/DetailSection.tsx
  react/src/pages/utils/components/InfoList.tsx
  react/src/pages/utils/components/components.tsx
  react/src/pages/utils/functions.tsx
  react/src/pages/utils/typings.tsx
Labels: frontend

#151 Flask: add DELETE /api/tissue_samples/:id
  flask/app/manage.py
  flask/app/routes.py
Labels: backend

#152 Flask: Split generic PATCH function for datasets, analyses and participants
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/participants.py
  flask/app/routes.py
Labels: backend

#153 React: Fix app bar height
  react/src/pages/Navigation.tsx
Labels: bug, frontend

#148 React: Replace upload page with add participant page
  react/src/pages/Navigation.tsx
  react/src/pages/addParticipants/AddParticipants.tsx
Labels: frontend

#147 React: Data Entry Table for Upload Page
  react/src/pages/addParticipants/AddParticipants.tsx
  react/src/pages/upload/UploadForm.tsx
  react/src/pages/upload/Uploads.tsx
  react/src/pages/utils/functions.tsx
  react/src/pages/utils/typings.tsx
  react/src/pages/utils/upload/DataEntryTable.tsx
  react/src/pages/utils/upload/FilesTable.tsx
  react/src/pages/utils/upload/UploadCSV.tsx
  react/src/pages/utils/upload/UploadDialog.tsx
  react/src/pages/utils/upload/UploadUtils.tsx
Labels: frontend

#170 React add participants: Disable adding values to enumerable columns
  react/src/pages/utils/upload/DataEntryTable.tsx
  react/src/pages/utils/upload/UploadUtils.tsx
Labels: frontend

#171 React: Add empty row button for data entry table
  react/src/pages/addParticipants/AddParticipants.tsx
  react/src/pages/participants/SampleTable.tsx
  react/src/pages/utils/functions.tsx
  react/src/pages/utils/typings.tsx
  react/src/pages/utils/upload/DataEntryTable.tsx
Labels: frontend

#176 CI: add pull request labeller workflow
  .editorconfig
  .github/labels.yml
  .github/workflows/label.yml
Labels: devops

#172 Flask: add MinIO administration module
  flask/Dockerfile
  flask/app/madmin.py
  flask/tests/test_madmin.py
Labels: backend, dependencies

#173 React Add participants: Checkbox cell for boolean headers
  react/src/pages/utils/upload/DataEntryTable.tsx
  react/src/pages/utils/upload/UploadUtils.tsx
Labels: frontend

#175 Flask: Create MinIO unlinked files endpoint
  flask/app/buckets.py
  flask/app/models.py
Labels: backend

#180 Flask: extend _bulk endpoint to accept json
  flask/app/routes.py
Labels: backend

#185 React: Fix lint warnings
  react/src/pages/Notification.tsx
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/datasets/AnalysisRunnerDialog.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/participants/ParticipantTable.tsx
Labels: frontend

#177 CI: add frontend workflow
  .github/workflows/react.yml
  react/package.json
  react/src/pages/utils/upload/DataEntryTable.tsx
Labels: devops, frontend

#183 Flask: add POST /api/families
  flask/app/families.py
  flask/app/routes.py
Labels: backend

#182 React: Data entry table date picker cells
  react/src/pages/addParticipants/AddParticipants.tsx
  react/src/pages/addParticipants/DataEntryTable.tsx
  react/src/pages/addParticipants/TableCells.tsx
  react/src/pages/addParticipants/UploadCSV.tsx
  react/src/pages/addParticipants/UploadDialog.tsx
  react/src/pages/addParticipants/utils.tsx
Labels: frontend

#178 Flask: POST /api/tissue_samples
  flask/app/routes.py
Labels: backend

#181 React: Add link to tables from info dialogs
  react/src/pages/Navigation.tsx
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/datasets/DatasetInfoDialog.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/participants/ParticipantInfoDialog.tsx
  react/src/pages/participants/ParticipantTable.tsx
  react/src/pages/participants/SampleTable.tsx
  react/src/pages/utils/components/AnalysisInfoDialog.tsx
  react/src/pages/utils/components/DetailSection.tsx
  react/src/pages/utils/components/InfoList.tsx
  react/src/pages/utils/functions.tsx
  react/src/pages/utils/typings.tsx
Labels: frontend

#187 Flask: POST /api/datasets
  flask/app/datasets.py
Labels: backend

#189 Flask: add POST /api/participants
  flask/app/participants.py
Labels: backend

#186 React: link dataset metadata with unlinked files
  react/src/pages/addParticipants/DataEntryTable.tsx
  react/src/pages/addParticipants/utils.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/utils/typings.tsx
Labels: frontend

#190 React: Edit functionality in dialogs
  react/src/pages/datasets/DatasetInfoDialog.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/participants/ParticipantInfoDialog.tsx
  react/src/pages/participants/ParticipantTable.tsx
  react/src/pages/participants/SampleTable.tsx
  react/src/pages/utils/components/AnalysisInfoDialog.tsx
  react/src/pages/utils/components/DetailSection.tsx
  react/src/pages/utils/components/InfoList.tsx
  react/src/pages/utils/functions.tsx
  react/src/pages/utils/typings.tsx
Labels: frontend

#196 React: Add typing for Family
  react/src/pages/addParticipants/DataEntryTable.tsx
  react/src/pages/addParticipants/utils.tsx
  react/src/pages/utils/typings.tsx
Labels: frontend

#184 Flask: Permission Gating
  README.md
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/families.py
  flask/app/madmin.py
  flask/app/models.py
  flask/app/participants.py
  flask/app/routes.py
Labels: backend, database, documentation

#197 adding constraints to groupname to match minio rules
  flask/app/manage.py
  flask/app/models.py
  flask/migrations/versions/567a9f6ac119_adding_constraints_to_groupname.py
Labels: database

#198 Flask: Fix broken endpoint
  flask/app/families.py
Labels: backend, bug

#194 React: New administration/users page
  react/src/pages/admin/Admin.tsx
  react/src/pages/admin/CreateUserModal.tsx
  react/src/pages/admin/UserDetails.tsx
  react/src/pages/admin/UserList.tsx
  react/src/pages/admin/UserRow.tsx
  react/src/pages/utils/components/ChipGroup.tsx
  react/src/pages/utils/components/ChipTransferList.tsx
  react/src/pages/utils/components/LastLoginDisplay.tsx
  react/src/pages/utils/components/NewPasswordForm.tsx
  react/src/pages/utils/components/SecretDisplay.tsx
  react/src/pages/utils/typings.tsx
Labels: frontend

#204 React: small tweaks
  react/src/pages/Navigation.tsx
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/datasets/Datasets.tsx
  react/src/pages/participants/Participants.tsx
  react/src/pages/settings/Settings.tsx
Labels: frontend

#211 Flask: remove api/objects
  flask/app/buckets.py
Labels: backend

#195 Flask: limit number of families returned
  flask/app/families.py
Labels: backend

#200 Flask: add query parameters to GET api/participants
  flask/app/participants.py
Labels: backend

#213 React: Group management component for admin page
  react/src/pages/admin/UserDetails.tsx
  react/src/pages/utils/components/ChipSelect.tsx
Labels: frontend

#235 React: Navigation refactor & misc cosmetic changes
  react/src/pages/Navigation.tsx
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/participants/ParticipantInfoDialog.tsx
  react/src/pages/participants/ParticipantTable.tsx
  react/src/pages/participants/SampleTable.tsx
Labels: frontend
