Repository ccmbioinfo/stager, pull requests merged in 2020-10, with the labels that each got.

#35 Add last_login timestamp in database and update on login
  flask/app/models.py
  flask/app/routes.py
  flask/migrations/versions/f8862eed0498_adding_last_login_to_user_table.py
Labels: database

#59 Retrieve usernames for all analyses in one query with three joins
  flask/app/routes.py
Labels: backend

#57 Flask: GET /api/participants, /api/datasets, /api/analyses, /api/pipelines
  flask/app/models.py
  flask/app/routes.py
Labels: backend

#56 Analysis page layout changes
  react/src/pages/Navigation.tsx
  react/src/pages/analysis/Analysis.tsx
  react/src/pages/analysis/AnalysisInfoDialog.tsx
  react/src/pages/dashboard/Dashboard.tsx
  react/src/pages/dashboard/Notification.tsx
  react/src/pages/dashboard/NotificationPanel.tsx
Labels: frontend

#61 Flask: add GET /api/enums
  flask/app/routes.py
Labels: backend

#26 React: change participants page to show datasets
  react/src/pages/Card.tsx
  react/src/pages/Navigation.tsx
  react/src/pages/admin/ManagedUploaders.tsx
  react/src/pages/analysis/AddAnalysisAlert.tsx
  react/src/pages/analysis/Analysis.tsx
  react/src/pages/analysis/CancelAnalysisDialog.tsx
  react/src/pages/datasets/AnalysisRunnerDialog.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/datasets/Datasets.tsx
  react/src/pages/participants/AnalysisRunnerDialog.tsx
  react/src/pages/participants/ParticipantsTable.tsx
  react/src/pages/upload/Uploads.tsx
  react/tsconfig.json
Labels: frontend

#58 React: switch dashboard to show participant table with copy buttons for combined codenames
  react/src/pages/dashboard/Dashboard.tsx
  react/src/pages/dashboard/DatasetType.tsx
  react/src/pages/dashboard/DatasetTypes.tsx
  react/src/pages/dashboard/MockData.tsx
  react/src/pages/dashboard/Notification.tsx
  react/src/pages/dashboard/NotificationPanel.tsx
  react/src/pages/dashboard/ParticipantTable.tsx
  react/src/pages/dashboard/SamplesTable.tsx
Labels: frontend

#64 Adding month of birth to participant table
  flask/app/manage.py
  flask/app/models.py
  flask/migrations/versions/0e8799c17f5a_adding_month_of_birth_field_with_check.py
Labels: database

#62 Analysis Page Action Buttons
  react/src/pages/analysis/Analysis.tsx
  react/src/pages/analysis/CancelAnalysisDialog.tsx
  react/src/pages/analysis/SetAssigneeDialog.tsx
  react/src/pages/dashboard/Notification.tsx
Labels: frontend

#67 Fix hardcoded database name in migration
  flask/migrations/versions/0e8799c17f5a_adding_month_of_birth_field_with_check.py
Labels: bug, database

#69 React: add participant detail modal on clicking dashboard rows
  react/src/pages/dashboard/AnalysisTable.tsx
  react/src/pages/dashboard/DatasetAccordion.tsx
  react/src/pages/dashboard/DatasetType.tsx
  react/src/pages/dashboard/DatasetTypes.tsx
  react/src/pages/dashboard/MockData.tsx
  react/src/pages/dashboard/ParticipantDetailDialog.tsx
  react/src/pages/dashboard/ParticipantTable.tsx
  react/src/pages/dashboard/SampleTable.tsx
Labels: frontend

#63 Flask: GET analysis by updated date
  flask/app/manage.py
  flask/app/routes.py
Labels: backend

#73 Fix visibility button not working unless selected
  react/src/pages/analysis/Analysis.tsx
Labels: bug, frontend

#66 Add utils.tsx
  react/src/pages/analysis/CancelAnalysisDialog.tsx
  react/src/pages/dashboard/ParticipantTable.tsx
  react/src/pages/datasets/AnalysisRunnerDialog.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/utils.tsx
Labels: frontend

#71 React: hook up datasets page to backend
  react/src/pages/datasets/AnalysisRunnerDialog.tsx
  react/src/pages/datasets/DatasetTable.tsx
Labels: frontend

#86 React: Dashboard fetch participants from backend
  react/src/pages/dashboard/AnalysisTable.tsx
  react/src/pages/dashboard/Dashboard.tsx
  react/src/pages/dashboard/DatasetAccordion.tsx
  react/src/pages/dashboard/MockData.tsx
  react/src/pages/dashboard/ParticipantDetailDialog.tsx
  react/src/pages/dashboard/ParticipantTable.tsx
  react/src/pages/dashboard/SampleTable.tsx
Labels: frontend

#89 add datasets_analyses table to dummy data
  flask/app/manage.py
Labels: database

#68 Flask: add POST /api/_bulk
  flask/app/routes.py
  flask/requirements-dev.txt
  flask/requirements.in
  flask/requirements.txt
Labels: backend, dependencies

#90 React: reduce font size, drawer width, app bar height
  react/src/App.tsx
  react/src/pages/Navigation.tsx
  react/src/pages/dashboard/Dashboard.tsx
  react/src/pages/dashboard/ParticipantTable.tsx
Labels: frontend

#94 ISO Date formatting (#82) and editable cells (#79)
  react/src/pages/analysis/Analysis.tsx
  react/src/pages/dashboard/AnalysisTable.tsx
  react/src/pages/dashboard/SampleTable.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/upload/FilesTable.tsx
  react/src/pages/utils.tsx
Labels: frontend

#92 React: new notification panel & connect it to backend
  react/src/App.tsx
  react/src/pages/Login.tsx
  react/src/pages/Navigation.tsx
  react/src/pages/Notification.tsx
  react/src/pages/NotificationPopover.tsx
  react/src/pages/analysis/Analysis.tsx
  react/src/pages/dashboard/Dashboard.tsx
  react/src/pages/dashboard/NotificationPanel.tsx
  react/src/pages/dashboard/ParticipantTable.tsx
Labels: frontend

#91 Flask: fix PATCH /api/analyses/:id to accept string usernames
  flask/app/models.py
  flask/app/routes.py
Labels: backend

#96 Flask: POST endpoint for analyses /api/analyses
  flask/app/routes.py
Labels: backend

#95 React: hook up analysis table rows, set assignee
  react/src/pages/analysis/Analysis.tsx
Labels: frontend

#100 React: collapse navigation drawer by default
  react/src/pages/Navigation.tsx
Labels: frontend

#97 React: provide user feedback via Snackbars via notistack library
  react/package.json
  react/src/App.tsx
  react/src/pages/analysis/Analysis.tsx
  react/src/pages/analysis/CancelAnalysisDialog.tsx
  react/src/pages/datasets/AnalysisRunnerDialog.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/utils.tsx
  react/yarn.lock
Labels: dependencies, frontend

#101 React: tidy imports, fix compiler warnings
  react/src/pages/analysis/Analysis.tsx
  react/src/pages/dashboard/ParticipantTable.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/upload/FilesTable.tsx
  react/src/pages/upload/UploadDialog.tsx
  react/src/pages/upload/UploadForm.tsx
Labels: frontend

#102 React: refactor duplicate code, remove SlideUpTransition
  react/src/pages/Navigation.tsx
  react/src/pages/Notification.tsx
  react/src/pages/NotificationPopover.tsx
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/analysis/AnalysisInfoDialog.tsx
  react/src/pages/analysis/CancelAnalysisDialog.tsx
  react/src/pages/analysis/DatasetTable.tsx
  react/src/pages/analysis/SetAssigneeDialog.tsx
  react/src/pages/dashboard/AnalysisTable.tsx
  react/src/pages/dashboard/DatasetAccordion.tsx
  react/src/pages/dashboard/MockData.tsx
  react/src/pages/dashboard/ParticipantDetailDialog.tsx
  react/src/pages/dashboard/ParticipantTable.tsx
  react/src/pages/dashboard/SampleTable.tsx
  react/src/pages/datasets/AnalysisRunnerDialog.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/datasets/Datasets.tsx
  react/src/pages/utils.tsx
Labels: frontend

#60 React: add CSV uploads via react-file-drop library
  react/package.json
  react/src/pages/upload/UploadCSV.tsx
  react/src/pages/upload/UploadDialog.tsx
  react/src/pages/upload/UploadForm.tsx
  react/src/pages/upload/Uploads.tsx
  react/yarn.lock
Labels: dependencies, frontend

#103 React: upgrade dependencies, drop unused react-table
  docker-compose.prod.yaml
  react/package.json
  react/yarn.lock
Labels: bug, frontend

#104 React: hook up analysis table run / cancel analyses
  react/src/pages/Notification.tsx
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/analysis/AnalysisInfoDialog.tsx
  react/src/pages/utils.tsx
Labels: frontend

#105 React: move up analysis info dialog with notifications; remove /analysis/:id route
  react/src/pages/AnalysisInfoDialog.tsx
  react/src/pages/Navigation.tsx
  react/src/pages/Notification.tsx
  react/src/pages/NotificationPopover.tsx
  react/src/pages/analysis/Analyses.tsx
Labels: frontend

#106 Flask: add GET /api/analyses/:id
  flask/app/models.py
  flask/app/routes.py
Labels: backend

#108 React: Change page name and icon
  react/src/pages/Navigation.tsx
  react/src/pages/participants/AnalysisTable.tsx
  react/src/pages/participants/DatasetAccordion.tsx
  react/src/pages/participants/DatasetTypes.tsx
  react/src/pages/participants/ParticipantDetailDialog.tsx
  react/src/pages/participants/ParticipantTable.tsx
  react/src/pages/participants/Participants.tsx
  react/src/pages/participants/SampleTable.tsx
Labels: frontend

#109 React: Datasets modal; view details
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/datasets/DatasetInfoDialog.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/datasets/DialogSections.tsx
  react/src/pages/participants/AnalysisTable.tsx
  react/src/pages/participants/SampleTable.tsx
  react/src/pages/utils.tsx
Labels: frontend

#124 React: hook up request analysis to backend
  flask/app/routes.py
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/datasets/AnalysisRunnerDialog.tsx
Labels: frontend

#126 React: add notification badge
  react/src/pages/NotificationPopover.tsx
Labels: frontend

#72 Backend rework and Login test cases
  flask/app/__init__.py
  flask/app/buckets.py
  flask/app/config.py
  flask/app/manage.py
  flask/app/models.py
  flask/app/routes.py
  flask/requirements-dev.in
  flask/requirements-dev.txt
  flask/tests/conftest.py
  flask/tests/test_login.py
  flask/utils/run.sh
  flask/wsgi.py
Labels: backend, dependencies

#127 React: hook up analysis details to backend
  react/src/pages/AnalysisInfoDialog.tsx
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/datasets/DialogSections.tsx
  react/src/pages/utils.tsx
Labels: frontend
