Repository ccmbioinfo/stager, pull requests merged in 2020-09, with the labels that each got.

#23 React: package security by removing unused material-dashboard-react
  react/package.json
  react/yarn.lock
Labels: dependencies, frontend

#27 Per-column table filtering
  react/src/pages/analysis/Analysis.tsx
  react/src/pages/analysis/DatasetTable.tsx
  react/src/pages/dashboard/AnalysisTable.tsx
  react/src/pages/dashboard/SamplesTable.tsx
  react/src/pages/participants/ParticipantsTable.tsx
  react/src/pages/upload/FilesTable.tsx
Labels: frontend

#30 Flask: log queries via SQLAlchemy to console
  flask/app/__init__.py
Labels: backend

#29 Flask: add PATCH /api/participants/<id>
  flask/app/models.py
  flask/app/routes.py
Labels: backend

#28 update page name to match the current page
  react/src/pages/Navigation.tsx
Labels: frontend

#34 Dialog guiding users from Analysis to Participants when creating new analysis
  react/src/pages/analysis/AddAnalysisAlert.tsx
  react/src/pages/analysis/Analysis.tsx
Labels: frontend

#37 Flask: PATCH /api/participants/:id, /api/datasets/:id, /api/analyses/:id in one function
  flask/app/routes.py
Labels: backend

#36 React: add collapsible notification panel on dashboard
  react/package.json
  react/src/pages/Navigation.tsx
  react/src/pages/analysis/Analysis.tsx
  react/src/pages/dashboard/AnalysisTable.tsx
  react/src/pages/dashboard/Dashboard.tsx
  react/src/pages/dashboard/Notification.tsx
  react/src/pages/dashboard/NotificationPanel.tsx
  react/yarn.lock
Labels: dependencies, frontend
