Repository ccmbioinfo/stager, pull requests merged in 2020-12, with the labels that each got.

#236 React: Hook up add participants submit button
  react/src/pages/addParticipants/AddParticipants.tsx
  react/src/pages/addParticipants/DataEntryTable.tsx
  react/src/pages/addParticipants/TableCells.tsx
  react/src/pages/admin/UserDetails.tsx
  react/src/pages/utils/components/ConfirmModal.tsx
  react/src/pages/utils/functions.tsx
  react/src/pages/utils/typings.tsx
Labels: frontend

#237 React: Fix notes changing table row height
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/participants/ParticipantTable.tsx
  react/src/pages/utils/components/Note.tsx
Labels: frontend

#243 db: add MinIO credentials to User table
  README.md
  flask/app/models.py
  flask/migrations/versions/8de51438e585_add_minio_credentials_to_user_table.py
Labels: database, documentation

#238 React: dark mode
  react/src/App.tsx
  react/src/pages/Login.tsx
  react/src/pages/Navigation.tsx
  react/src/pages/NotificationPopover.tsx
  react/src/pages/admin/Admin.tsx
  react/src/pages/admin/CreateUserModal.tsx
Labels: frontend

#199 Flask: add unit tests for all endpoints
  flask/app/__init__.py
  flask/app/analyses.py
  flask/app/config.py
  flask/app/datasets.py
  flask/app/families.py
  flask/app/participants.py
  flask/app/routes.py
  flask/tests/badsamplecsv.csv
  flask/tests/conftest.py
  flask/tests/samplecsv.csv
  flask/tests/test_analyses.py
  flask/tests/test_datasets.py
  flask/tests/test_families.py
  flask/tests/test_login.py
  flask/tests/test_misc.py
  flask/tests/test_participants.py
  flask/tests/test_samples.py
Labels: backend, tests

#239 React: Save default columns for Add Participants page
  react/src/pages/addParticipants/DataEntryTable.tsx
Labels: frontend

#245 React: Fix 'Pipeline: undefined undefined' issue in analysis dialogs
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/participants/ParticipantTable.tsx
  react/src/pages/utils/components/DetailSection.tsx
Labels: bug, frontend

#247 nginx: forward MinIO on port 9000, other production fixes
  Dockerfile
  docker-compose.prod.yaml
  docker-compose.test.yaml
  docker-compose.yaml
  nginx/conf.d/default.conf
Labels: bug, devops

#251 Test Scoping
  flask/tests/conftest.py
Labels: backend, tests

#244 Flask: migrations for *_by schema changes
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/families.py
  flask/app/manage.py
  flask/app/models.py
  flask/app/participants.py
  flask/app/routes.py
  flask/migrations/versions/403cfa4b6184_alter_analysis_table_field_names_for_.py
  flask/migrations/versions/4a075eaadd1a_add_user_relationships_and_rename_fields.py
  flask/tests/conftest.py
  flask/tests/test_datasets.py
  flask/tests/test_participants.py
  flask/tests/test_samples.py
Labels: backend, database, tests

#246 Flask: Groups endpoints
  flask/app/__init__.py
  flask/app/groups.py
  flask/tests/conftest.py
  flask/tests/test_groups.py
Labels: backend, tests

#241 PATCH /api/tissue_samples/:id
  flask/app/__init__.py
  flask/app/routes.py
  flask/app/tissue_samples.py
  flask/tests/test_samples.py
Labels: backend, tests

#240 React: CSV export button for all tables
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/participants/ParticipantTable.tsx
  react/src/pages/utils/functions.tsx
Labels: frontend

#252 Flask & React: Display pipeline name, version instead of id on analyses page
  flask/app/analyses.py
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/utils/typings.tsx
Labels: backend, frontend

#254 React: autopopulate if selecting existing participants on add dataset page
  react/src/pages/addParticipants/DataEntryTable.tsx
  react/src/pages/addParticipants/TableCells.tsx
  react/src/pages/addParticipants/utils.tsx
  react/src/pages/utils/typings.tsx
Labels: frontend

#262 React: add snackbar feedback for CSV upload
  react/src/pages/addParticipants/UploadDialog.tsx
Labels: frontend

#265 Flask & React: upgrade dependencies
  flask/app/buckets.py
  flask/requirements-dev.txt
  flask/requirements.txt
  react/package.json
  react/src/pages/admin/UserRow.tsx
  react/src/pages/analysis/Analyses.tsx
  react/tsconfig.json
  react/yarn.lock
Labels: backend, dependencies, frontend

#249 React: Components for handling boolean/null in material-table
  react/src/pages/datasets/DatasetTable.tsx
  react/src/pages/participants/ParticipantInfoDialog.tsx
  react/src/pages/participants/ParticipantTable.tsx
  react/src/pages/utils/components/BooleanDisplay.tsx
  react/src/pages/utils/components/BooleanEditComponent.tsx
  react/src/pages/utils/components/BooleanFilter.tsx
  react/src/pages/utils/components/DetailSection.tsx
  react/src/pages/utils/functions.tsx
  react/src/pages/utils/typings.tsx
Labels: frontend

#248 React: support linking multiple files per dataset
  react/src/pages/addParticipants/DataEntryTable.tsx
  react/src/pages/addParticipants/TableCells.tsx
  react/src/pages/addParticipants/utils.tsx
  react/src/pages/utils/typings.tsx
Labels: frontend

#261 Flask: return usernames for all endpoints
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/families.py
  flask/app/models.py
  flask/app/participants.py
  flask/app/tissue_samples.py
  flask/tests/test_datasets.py
  flask/tests/test_samples.py
Labels: backend, database, tests

#253 Flask: support linking multiple files per dataset
  flask/app/analyses.py
  flask/app/buckets.py
  flask/app/datasets.py
  flask/app/manage.py
  flask/app/models.py
  flask/app/routes.py
  flask/migrations/versions/a8abbee2352a_multiple_files_per_dataset.py
  flask/tests/test_analyses.py
  flask/tests/test_datasets.py
  flask/tests/test_misc.py
  react/src/pages/analysis/Analyses.tsx
  react/src/pages/utils/functions.tsx
  react/src/pages/utils/typings.tsx
Labels: backend, database, frontend, tests

#266 React: Detail Dialog refactor
  react/src/pages/datasets/DatasetInfoDialog.tsx
  react/src/pages/participants/ParticipantInfoDialog.tsx
  react/src/pages/participants/SampleTable.tsx
  react/src/pages/utils/components/AnalysisInfoDialog.tsx
  react/src/pages/utils/components/DetailSection.tsx
  react/src/pages/utils/components/FieldDisplay.tsx
  react/src/pages/utils/components/FieldDisplayEditable.tsx
  react/src/pages/utils/components/GridFieldsDisplay.tsx
  react/src/pages/utils/components/InfoList.tsx
  react/src/pages/utils/functions.tsx
Labels: frontend

#267 Flask: update GET /api/users, move to users.py, add tests
  flask/app/__init__.py
  flask/app/routes.py
  flask/app/users.py
  flask/tests/test_users.py
  react/src/pages/admin/CreateUserModal.tsx
  react/src/pages/admin/UserDetails.tsx
  react/src/pages/admin/UserList.tsx
  react/src/pages/admin/UserRow.tsx
  react/src/pages/utils/components/ChipSelect.tsx
  react/src/pages/utils/typings.tsx
Labels: backend, frontend, tests

#268 Flask: add GET, POST /api/users/:username
  flask/app/users.py
  flask/tests/test_users.py
Labels: backend, tests

#272 React: use type disjunction in UserList reducer
  react/src/Admin/components/UserList.tsx
Labels: frontend

#269 Flask & React: update POST /api/users, user creation form
  flask/app/routes.py
  flask/app/users.py
  flask/tests/conftest.py
  flask/tests/test_users.py
  react/src/Admin/components/CreateUserModal.tsx
  react/src/Admin/components/UserList.tsx
Labels: backend, frontend, tests

#271 React: resizable table columns on add dataset page
  react/package.json
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/components/TableCells.tsx
  react/yarn.lock
Labels: dependencies, frontend

#263 Require sequencing_date at the API level but not the database level
  flask/app/datasets.py
  flask/app/routes.py
  flask/tests/samplecsv.csv
  flask/tests/test_datasets.py
  flask/tests/test_misc.py
  react/src/AddDatasets/components/DataEntryTable.tsx
Labels: backend, frontend, tests

#274 React: Hide admin pages and dataset delete
  flask/app/routes.py
  react/src/App.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Datasets/index.tsx
  react/src/Login.tsx
  react/src/Navigation.tsx
Labels: backend, frontend

#276 Flask: blueprints re-factor, extract helpers and separate extensions
  flask/app/__init__.py
  flask/app/analyses.py
  flask/app/buckets.py
  flask/app/datasets.py
  flask/app/extensions.py
  flask/app/families.py
  flask/app/groups.py
  flask/app/manage.py
  flask/app/participants.py
  flask/app/routes.py
  flask/app/tissue_samples.py
  flask/app/users.py
  flask/app/utils.py
Labels: backend, database

#275 React: Hookup admin, settings pages
  react/src/Admin/components/CreateUserModal.tsx
  react/src/Admin/components/GroupSelect.tsx
  react/src/Admin/components/UserDetails.tsx
  react/src/Admin/components/UserList.tsx
  react/src/Admin/components/UserRow.tsx
  react/src/Settings/index.tsx
  react/src/components/ChipSelect.tsx
  react/src/components/MinioKeyDisplay.tsx
  react/src/components/MinioResetButton.tsx
  react/src/components/SecretDisplay.tsx
  react/src/components/index.tsx
  react/src/typings.tsx
Labels: frontend

#278 Flask: initialize MinIO policies for groups in dummy data
  Dockerfile
  docker-compose.prod.yaml
  docker-compose.yaml
  flask/Dockerfile
  flask/app/manage.py
  react/.gitignore
Labels: backend, database, devops

#285 React: link to MinIO
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/Settings/index.tsx
Labels: frontend

#286 Flask: update DELETE /api/users to DELETE /api/users/:username
  flask/app/routes.py
  flask/app/users.py
  flask/tests/test_users.py
  react/src/Admin/components/UserList.tsx
Labels: backend, frontend, tests

#288 React: useEnums hook for retrieving cached /api/enums result
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/App.tsx
  react/src/Datasets/components/DatasetInfoDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/contexts/enums/EnumContext.tsx
  react/src/contexts/enums/EnumProvider.tsx
  react/src/contexts/enums/index.tsx
  react/src/contexts/enums/useEnums.tsx
  react/src/typings.tsx
Labels: frontend

#287 Additional DB Changes
  flask/app/models.py
  flask/migrations/versions/2a2bc309568d_initial_migration.py
Labels: database
