Repository ccmbioinfo/stager, pull requests merged in 2021-08, with the labels that each got.

#755 React: Remove deprecated material-ui code
  react/src/Admin/components/UserRow.tsx
  react/src/App.tsx
  react/src/Login.tsx
  react/src/components/DetailSection.tsx
  react/src/components/SecretDisplay.tsx
Labels: frontend

#767 Docs: instructions for linking third-party IdPs to Keycloak
  docs/keycloak.md
Labels: documentation

#769 Flask/DB: Drop deprecated dataset_file table and update models
  flask/app/models.py
  flask/migrations/versions/6f448fc94a2d_many_to_many_dataset_files.py
  flask/migrations/versions/b7e6ad115b13_drop_old_dataset_file_table.py
Labels: database
