Repository ccmbioinfo/stager, pull requests merged in 2021-10, with the labels that each got.

#845 Flask: fix mixin column coverage
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/utils.py
  flask/tests/test_datasets.py
  flask/tests/unit/test_mixin.py
Labels: backend, tests

#843 React/Flask: Fix datasets editing modal (#814)
  flask/app/datasets.py
  react/src/components/DetailSection.tsx
  react/src/components/FieldDisplayEditable.tsx
  react/src/functions.tsx
  react/src/typings.tsx
Labels: backend, frontend

#852 Flask: fix sequencing_id in _bulk and GET analyses
  flask/app/analyses.py
  flask/app/routes.py
Labels: backend

#879 gitattributes: don't treat all files as text
  .gitattributes
Labels: bug

#882 CI: rewrite backend workflow to be push-based
  .github/workflows/flask.yml
  docker-compose.cheo.yaml
Labels: devops
