Repository ccmbioinfo/stager, pull requests merged in 2021-03, with the labels that each got.

#416 React: Add date filter component for datasets, analyses
  react/package.json
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/components/DateFilterComponent.tsx
  react/src/components/index.tsx
  react/yarn.lock
Labels: dependencies, frontend

#428 Docker: provide ST_SECRET_KEY, bake FLASK_ENV into image
  Dockerfile
  docker-compose.prod.yaml
  docker-compose.test.yaml
  docker-compose.yaml
  flask/Dockerfile
  sample.env
Labels: backend, bug, devops

#421 Flask: embed GIT_SHA in image, add /api to retrieve
  .github/workflows/flask.yml
  Dockerfile
  docker-compose.prod.yaml
  flask/app/config.py
  flask/app/models.py
  flask/app/routes.py
Labels: backend, database, devops

#429 Flask: logging to user endpoints
  flask/app/users.py
Labels: backend

#430 React: Update datasets table to use progressive loading
  flask/app/datasets.py
  react/src/Datasets/components/DatasetTable.tsx
  react/src/hooks/datasets/useDatasetCreateMutation.tsx
  react/src/hooks/datasets/useDatasetDeleteMutation.tsx
  react/src/hooks/datasets/useDatasetUpdateMutation.tsx
Labels: backend, frontend

#432 Flask: prevent admin from deleting self
  flask/app/users.py
  flask/tests/test_users.py
Labels: backend, tests

#433 React: Disable delete user button for self
  react/src/Admin/components/UserDetails.tsx
Labels: frontend

#406 Flask: implement progressive loading and filtering on /api/analyses
  flask/app/analyses.py
  flask/app/models.py
  flask/tests/test_analyses.py
Labels: backend, database, tests

#442 React: Add pipeline filter for analyses page
  react/src/Analyses/components/PipelineFilter.tsx
  react/src/Analyses/index.tsx
  react/src/components/NotificationPopover.tsx
  react/src/hooks/analyses/useAnalysesPage.tsx
  react/src/hooks/analyses/useAnalysesQuery.tsx
  react/src/hooks/index.tsx
Labels: frontend

#443 Flask: update models.py and migrations for gene pull schema
  flask/app/models.py
  flask/migrations/versions/2fac0d8a5b76_model_gene_pull_schema.py
  flask/tests/test_misc.py
Labels: backend, database, tests

#449 CI: fix automatic labels for Dependabot and external PRs
  .github/workflows/label.yml
Labels: devops

#461 CI: only login to registry on push workflows
  .github/workflows/flask.yml
Labels: devops

#464 React: add REACT_APP_GIT_SHA env var to build script and print to console
  react/package.json
  react/src/App.tsx
Labels: frontend

#465 clear non-static query cache on logout
  react/src/App.tsx
  react/src/hooks/utils.tsx
Labels: frontend

#473 define inline functions and components to avoid rerenders
  react/src/Datasets/components/DatasetTable.tsx
Labels: frontend
