Repository ccmbioinfo/stager, pull requests merged in 2021-12, with the labels that each got.

#971 React: reinstate lab fetch after routing fix
  react/src/App.tsx
Labels: frontend

#947 Flask: implement email notifications
  .github/workflows/flask.yml
  docker-compose.cheo.yaml
  flask/app/__init__.py
  flask/app/email.py
  flask/app/tasks.py
  flask/requirements-dev.txt
  flask/requirements.in
  flask/requirements.txt
  flask/wsgi.py
  react/yarn.lock
  sample.env
Labels: backend, frontend, dependencies, devops

#973 CI: deploy CCM multi-Stager
  .github/workflows/flask.yml
  .github/workflows/react.yml
  docker-compose.ccm.yaml
  docker-compose.prod.yaml
  nginx/conf.d/default.conf
  react/src/hooks/utils.tsx
Labels: frontend, devops

#979 Flask/Minio: add MINIO_TLS env var to docker-compose.ccm
  docker-compose.ccm.yaml
Labels: devops

#978 Flask: fix security warning for 'starbank'
  flask/requirements-dev.txt
  flask/requirements.txt
Labels: backend, dependencies

#980 Flask: modified fields in notification email
  flask/app/tasks.py
Labels: backend

#959 SQLAlchemy: Upgrade to version 1.4.27
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/families.py
  flask/app/groups.py
  flask/app/models.py
  flask/app/participants.py
  flask/app/routes.py
  flask/app/utils.py
  flask/app/variants.py
  flask/migrations/versions/7a933f756ef9_non_nullable_discriminator.py
  flask/requirements-dev.txt
  flask/requirements.txt
Labels: backend, database, dependencies

#974 Flask: add marshmallow and a few schemas for input validation
  flask/app/__init__.py
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/extensions.py
  flask/app/families.py
  flask/app/participants.py
  flask/app/schemas.py
  flask/app/tissue_samples.py
  flask/requirements-dev.txt
  flask/requirements.in
  flask/requirements.txt
  flask/tests/test_analyses.py
  flask/tests/test_datasets.py
  flask/tests/test_participants.py
  flask/tests/test_samples.py
Labels: backend, dependencies, tests

#983 Flask: add Prometheus endpoint
  Dockerfile
  docker-compose.ccm.yaml
  docker-compose.cheo.yaml
  docker-compose.yaml
  flask/Dockerfile
  flask/app/__init__.py
  flask/app/extensions.py
  flask/gunicorn.conf.py
  flask/requirements-dev.txt
  flask/requirements.in
  flask/requirements.txt
Labels: backend, dependencies, devops

#982 React: Fix participant row editing and dataset_type filtering
  flask/app/participants.py
  react/src/Participants/components/ParticipantTable.tsx
Labels: backend, frontend

#975 Flask/React: update /api/unlinked to query by prefix only, debounce requests on frontend
  flask/app/buckets.py
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/components/TableCells.tsx
  react/src/AddDatasets/components/utils.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/components/AutocompleteMultiselect.tsx
  react/src/components/FieldDisplayEditable.tsx
  react/src/components/FileLinkingComponent.tsx
  react/src/hooks/index.tsx
  react/src/hooks/unlinked/useUnlinkedFilesQuery.tsx
  react/src/hooks/useDebounce.ts
Labels: backend, frontend

#986 React: Dynamic MinIO URL
  react/public/sample.labs.json
  react/src/AddDatasets/components/DataEntryToolbar.tsx
  react/src/App.tsx
  react/src/Settings/components/Instructions.tsx
  react/src/Settings/index.tsx
  react/src/components/LabDropdownSelect.tsx
  react/src/hooks/utils.tsx
  react/src/typings.tsx
Labels: frontend

#987 React: fix analysis requests broken by backend schema verification
  react/src/hooks/analyses/useAnalysisCreateMutation.tsx
Labels: bug, frontend
