Repository ccmbioinfo/stager, pull requests merged in 2021-06, with the labels that each got.

#636 CI: Reassign default dependabot reviews
  .github/dependabot.yml
Labels: devops

#632 Flask: Add logging to analysis endpoints
  flask/app/analyses.py
Labels: backend

#626 React: Refactor file select input to render minimal options
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/components/FileLinkingComponent.tsx
Labels: frontend

#635 Flask: support MINIO_REGION_NAME environment variable
  docker-compose.oidc.yaml
  docker-compose.prod.yaml
  docker-compose.test.yaml
  docker-compose.yaml
  flask/app/config.py
  flask/app/groups.py
  flask/app/manage.py
  flask/tests/conftest.py
  sample.env
Labels: backend, database, devops, tests

#631 Flask: Add MinIO permission group for Stager admins
  flask/app/manage.py
  flask/app/users.py
  flask/tests/test_groups.py
  flask/tests/test_madmin.py
Labels: backend, database, tests

#649 Flask & React: Log user out of OAuth session as well as Stager
  docs/oidc.md
  flask/app/routes.py
  react/src/Admin/components/CreateUserModal.tsx
  react/src/Admin/components/UserDetails.tsx
  react/src/App.tsx
  react/src/contexts/index.tsx
  react/src/contexts/useAPIInfoContext.tsx
  react/src/contexts/useOAuthContext.tsx
  react/src/typings.tsx
Labels: backend, documentation, frontend

#650 Flask: Add logging to groups endpoints
  flask/app/groups.py
Labels: backend

#651 Flask: Add logging to unlinked files endpoint
  flask/app/buckets.py
Labels: backend

#657 Flask: add column names as a list to ensure consistent ordering
  flask/app/variants.py
Labels: backend

#658 Flask: Allow sorting by analysis_id, dataset_id
  flask/app/analyses.py
  flask/app/datasets.py
Labels: backend

#660 React: Prevent login page from momentarily rendering on reload
  react/src/App.tsx
Labels: frontend

#662 React: Add descriptions to variant report types
  flask/app/variants.py
  react/src/SearchVariants/components/Autocomplete.tsx
  react/src/SearchVariants/components/CardButton.tsx
  react/src/SearchVariants/components/SearchVariantsPage.tsx
Labels: backend, frontend

#664 Flask & React: Filter by multi-value columns
  flask/app/datasets.py
  flask/app/participants.py
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantTable.tsx
Labels: backend, frontend

#665 Flask: changes, re-factoring endpoints for adding requested gene(s) to JSON and CSV
  flask/app/variants.py
  flask/tests/test_variants.py
Labels: backend, tests

#677 Flask/DB: Click command to reassociate analyses with correct pipelines
  flask/app/manage.py
Labels: database

#678 React: Align variant cards vertically
  react/src/SearchVariants/components/SearchVariantsPage.tsx
Labels: frontend

#675 Flask: Fix GET /api/datasets returning fewer rows than expected
  flask/app/datasets.py
  flask/tests/test_datasets.py
  react/src/Datasets/components/DatasetTable.tsx
  react/src/hooks/utils.tsx
Labels: backend, frontend, tests

#690 Flask/Minio: Remove Minio group policies from admins to prevent overrides
  flask/app/users.py
  flask/tests/test_users.py
Labels: backend, tests
