Repository ccmbioinfo/stager, pull requests merged in 2021-01, with the labels that each got.

#293 React: rename to Stager with app name in REACT_APP_NAME envvar
  README.md
  react/package.json
  react/public/index.html
  react/public/manifest.json
  react/src/AddDatasets/index.tsx
  react/src/Admin/components/UserList.tsx
  react/src/Analyses/index.tsx
  react/src/Datasets/index.tsx
  react/src/Login.tsx
  react/src/Participants/index.tsx
  react/src/Settings/index.tsx
Labels: documentation, frontend

#294 React: useFetchCache hook for caching any api call for session duration
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/Admin/components/CreateUserModal.tsx
  react/src/Admin/components/UserList.tsx
  react/src/Admin/components/UserRow.tsx
  react/src/App.tsx
  react/src/Datasets/components/DatasetInfoDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/contexts/EnumContext.tsx
  react/src/contexts/EnumProvider.tsx
  react/src/contexts/fetchCache/FetchCacheContext.tsx
  react/src/contexts/fetchCache/FetchCacheProvider.tsx
  react/src/contexts/fetchCache/index.tsx
  react/src/contexts/fetchCache/useFetchCache.tsx
  react/src/contexts/useEnums.tsx
Labels: frontend

#289 Flask: add PATCH /api/users/:username
  flask/app/routes.py
  flask/app/users.py
  flask/tests/test_users.py
  react/src/Admin/components/UserDetails.tsx
  react/src/Admin/components/UserList.tsx
  react/src/Settings/index.tsx
  react/src/components/NewPasswordForm.tsx
Labels: backend, frontend, tests

#291 /api/_bulk: add group query string parameter
  flask/app/routes.py
  flask/tests/conftest.py
  flask/tests/test_analyses.py
  flask/tests/test_families.py
  flask/tests/test_groups.py
  flask/tests/test_misc.py
  flask/tests/test_participants.py
  flask/tests/test_users.py
Labels: backend, tests

#298 React: Fix material-table filters being deleted upon first typing
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
Labels: frontend

#296 Flask: fix empty group deletion returning 422 on success
  flask/app/groups.py
Labels: backend, bug

#295 React: replace manage uploaders tab with group management page
  flask/app/groups.py
  react/src/Admin/components/HidableTextButton.tsx
  react/src/Admin/components/ManagedUploaders.tsx
  react/src/Admin/index.tsx
  react/src/Groups/components/CreateGroupModal.tsx
  react/src/Groups/components/Group.tsx
  react/src/Groups/index.tsx
  react/src/Navigation.tsx
Labels: backend, design, frontend

#297 React: Add render component for multiple files on Datasets page
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/components/TableCells.tsx
  react/src/AddDatasets/components/utils.tsx
  react/src/Admin/components/UserList.tsx
  react/src/Datasets/components/AnalysisRunnerDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Datasets/components/LinkedFilesButton.tsx
  react/src/Datasets/components/LinkedFilesPopover.tsx
  react/src/Participants/components/SampleTable.tsx
  react/src/functions.tsx
  react/src/typings.tsx
Labels: frontend

#299 React: hook up linking multiple files and make sequencing_date a required field
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/components/TableCells.tsx
  react/src/AddDatasets/components/utils.tsx
  react/src/Datasets/components/AnalysisRunnerDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/DatasetTypes.tsx
  react/src/components/FileLinkingComponent.tsx
  react/src/components/index.tsx
  react/src/functions.tsx
  react/src/typings.tsx
Labels: frontend

#302 React: Permission group multiselect in Add Datasets
  flask/app/routes.py
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/index.tsx
  react/src/App.tsx
  react/src/Login.tsx
  react/src/Navigation.tsx
  react/src/components/GroupDropdownSelect.tsx
  react/src/components/index.tsx
Labels: backend, frontend

#301 docs: separate from README and expand
  README.md
  docs/database.md
  docs/docker.md
  docs/flask.md
  docs/production.md
  docs/pycharm.md
  docs/react.md
  docs/vscode.md
Labels: documentation

#304 React & Flask: JSONEncoder for ISO datetimes, day.js for frontend datetimes
  flask/app/__init__.py
  flask/app/utils.py
  react/package.json
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/SampleTable.tsx
  react/src/components/DateTimeText.tsx
  react/src/components/index.tsx
  react/src/functions.tsx
  react/yarn.lock
Labels: backend, dependencies, frontend

#305 React: Fix empty string check in Add Datasets
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/components/TableCells.tsx
  react/src/AddDatasets/components/utils.tsx
  react/src/AddDatasets/index.tsx
  react/src/functions.tsx
Labels: frontend

#319 React: Fix permission group dropdown defaults in Add Datasets
  react/src/AddDatasets/index.tsx
Labels: frontend

#320 React: Fix persistent italics for reactivated users
  react/src/Admin/components/UserRow.tsx
Labels: frontend

#290 Flask: restrict user actions for analyses
  flask/app/analyses.py
  flask/tests/test_analyses.py
Labels: backend, tests

#322 CI: add CodeQL and Dependabot
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
Labels: devops

#335 React: Replace fetchCache context with react-query hooks
  react/package.json
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/Admin/components/CreateUserModal.tsx
  react/src/Admin/components/UserRow.tsx
  react/src/App.tsx
  react/src/Datasets/components/DatasetInfoDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/contexts/EnumContext.tsx
  react/src/contexts/EnumProvider.tsx
  react/src/contexts/enums/EnumContext.tsx
  react/src/contexts/enums/EnumProvider.tsx
  react/src/contexts/enums/index.tsx
  react/src/contexts/enums/useEnums.tsx
  react/src/contexts/fetchCache/FetchCacheContext.tsx
  react/src/contexts/fetchCache/FetchCacheProvider.tsx
  react/src/contexts/fetchCache/index.tsx
  react/src/contexts/fetchCache/useFetchCache.tsx
  react/src/contexts/useEnums.tsx
  react/src/hooks/index.tsx
  react/src/hooks/useEnums.tsx
  react/src/hooks/useGroups.tsx
  react/src/hooks/utils.tsx
  react/yarn.lock
Labels: dependencies, frontend

#321 Flask: add GET /api/metadatasettypes
  flask/app/routes.py
  flask/tests/conftest.py
  flask/tests/test_misc.py
Labels: backend, tests

#337 Flask: add GET api/institutions
  flask/app/routes.py
  flask/tests/conftest.py
  flask/tests/test_misc.py
Labels: backend, tests

#338 React: Refactor /api/groups hookup to use react-query
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/App.tsx
  react/src/Groups/components/CreateGroupModal.tsx
  react/src/Groups/components/Group.tsx
  react/src/Groups/index.tsx
  react/src/hooks/groups/useGroup.tsx
  react/src/hooks/groups/useGroups.tsx
  react/src/hooks/groups/useGroupsDelete.tsx
  react/src/hooks/groups/useGroupsPatch.tsx
  react/src/hooks/groups/useGroupsPost.tsx
  react/src/hooks/index.tsx
  react/src/hooks/useEnums.tsx
  react/src/hooks/useFamilies.tsx
  react/src/hooks/useGroups.tsx
Labels: frontend

#336 CI: add frontend deploy step on master
  .github/workflows/flask.yml
  .github/workflows/react.yml
  react/deploy.sh
Labels: devops, frontend

#345 CI: add backend deploy step on master
  .github/workflows/flask.yml
  Dockerfile
  docker-compose.prod.yaml
  docker-compose.test.yaml
  docker-compose.yaml
  flask/.dockerignore
  flask/Dockerfile
  flask/app/madmin.py
  nginx/conf.d/default.conf
  sample.env
Labels: backend, devops

#349 CI: build and push development image in separate steps
  .github/workflows/flask.yml
Labels: devops

#347 Flask: prevent deactivated users from signing in
  flask/app/routes.py
Labels: backend

#303 Flask: add limit, page, order_by, order_dir, filter parameters to /api/participants
  flask/app/participants.py
  flask/app/utils.py
Labels: backend

#346 Add institution field to APIs returning participants
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/families.py
  flask/app/participants.py
  flask/app/routes.py
Labels: backend

#348 Flask: restrict analysis requests based on dataset type and pipeline …
  flask/app/analyses.py
  flask/tests/conftest.py
  flask/tests/test_analyses.py
  flask/tests/test_misc.py
Labels: backend, tests

#350 React: Refactor /api/users hookup to use react-query
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/Admin/components/CreateUserModal.tsx
  react/src/Admin/components/GroupSelect.tsx
  react/src/Admin/components/UserDetails.tsx
  react/src/Admin/components/UserList.tsx
  react/src/Admin/components/UserRow.tsx
  react/src/Datasets/components/DatasetInfoDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Groups/components/CreateGroupModal.tsx
  react/src/Groups/components/Group.tsx
  react/src/Groups/index.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/Settings/index.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/components/MinioResetButton.tsx
  react/src/hooks/groups/useGroupCreateMutation.tsx
  react/src/hooks/groups/useGroupDeleteMutation.tsx
  react/src/hooks/groups/useGroupQuery.tsx
  react/src/hooks/groups/useGroupUpdateMutation.tsx
  react/src/hooks/groups/useGroupsDelete.tsx
  react/src/hooks/groups/useGroupsPatch.tsx
  react/src/hooks/groups/useGroupsPost.tsx
  react/src/hooks/groups/useGroupsQuery.tsx
  react/src/hooks/index.tsx
  react/src/hooks/useEnumsQuery.tsx
  react/src/hooks/useFamiliesQuery.tsx
  react/src/hooks/users/useUserMinioMutation.tsx
  react/src/hooks/users/useUserQuery.tsx
  react/src/hooks/users/useUsersCreateMutation.tsx
  react/src/hooks/users/useUsersDeleteMutation.tsx
  react/src/hooks/users/useUsersQuery.tsx
  react/src/hooks/users/useUsersUpdateMutation.tsx
  react/src/hooks/utils.tsx
  react/src/typings.tsx
Labels: frontend
