Repository ccmbioinfo/stager, pull requests merged in 2021-07, with the labels that each got.

#688 React: Update OAuth login flow for untracked users
  flask/app/manage.py
  flask/app/manage_keycloak.py
  flask/app/routes.py
  react/src/App.tsx
  react/src/Login.tsx
  react/src/Navigation.tsx
Labels: backend, database, frontend

#691 Flask/db: update schema to expand report column coverage
  docker-compose.yaml
  flask/.gitignore
  flask/app/manage.py
  flask/app/mapping_utils.py
  flask/app/models.py
  flask/app/variants.py
  flask/migrations/versions/99955a52d781_expand_column_coverage_for_reports.py
Labels: backend, database, devops

#700 Flask: Add gene alias column to export
  flask/app/variants.py
  flask/migrations/versions/184f5edd4719_add_index_to_gene_alias_ensembl_id.py
Labels: backend, database

#716 Flask: add traceback to error handler
  flask/app/error_handler.py
Labels: backend

#722 Flask/Docker: minor fixes and changes
  docker-compose.yaml
  flask/app/manage.py
Labels: database, devops

#698 React/Flask: Add support for multiplex files
  flask/app/buckets.py
  flask/app/datasets.py
  flask/app/models.py
  flask/app/routes.py
  flask/app/utils.py
  flask/migrations/versions/6f448fc94a2d_many_to_many_dataset_files.py
  flask/tests/test_datasets.py
  flask/tests/test_misc.py
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/components/DataEntryTableRow.tsx
  react/src/AddDatasets/components/TableCells.tsx
  react/src/AddDatasets/components/utils.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/SampleTable.tsx
  react/src/components/DateFilterComponent.tsx
  react/src/components/FileLinkingComponent.tsx
  react/src/components/Note.tsx
  react/src/components/SecretDisplay.tsx
  react/src/functions.tsx
  react/src/hooks/unlinked/useUnlinkedFilesQuery.tsx
  react/src/typings.tsx
Labels: backend, database, frontend, tests

#732 React: Create loading indicator for SearchVariants page
  react/src/SearchVariants/components/SearchVariantsPage.tsx
Labels: frontend

#745 Flask: Add linked_files to participants and analysis [get] payloads
  flask/app/analyses.py
  flask/app/participants.py
Labels: backend

#738 React: Standardize error handling
  react/src/AddDatasets/components/UploadDialog.tsx
  react/src/AddDatasets/index.tsx
  react/src/Admin/components/UserList.tsx
  react/src/Analyses/index.tsx
  react/src/App.tsx
  react/src/Datasets/components/AnalysisRunnerDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Groups/components/CreateGroupModal.tsx
  react/src/Groups/index.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/SearchVariants/components/SearchVariantsPage.tsx
  react/src/Settings/index.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/components/DetailSection.tsx
  react/src/hooks/index.tsx
  react/src/hooks/useErrorSnackbar.tsx
Labels: frontend

#717 Flask: Search for Variants by position, region; select columns
  flask/app/variants.py
  flask/tests/conftest.py
  flask/tests/test_variants.py
  react/src/SearchVariants/components/SearchVariantsPage.tsx
Labels: backend, frontend, tests

#729 React: Remove table filter cache and add remove all filters button
  react/src/Analyses/components/PipelineFilter.tsx
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/components/BooleanFilter.tsx
  react/src/functions.tsx
  react/src/hooks/index.tsx
  react/src/hooks/useTableFilterCache.tsx
Labels: frontend

#687 React: Variant export enhancements for frontend
  react/src/SearchVariants/components/Autocomplete.tsx
  react/src/SearchVariants/components/ReportColumnModal.tsx
  react/src/SearchVariants/components/SearchVariantsPage.tsx
  react/src/hooks/index.tsx
  react/src/hooks/useModalState.tsx
Labels: frontend

#756 Flask/Database: Add index to Variant.position
  flask/app/models.py
  flask/migrations/versions/45ed820bb437_add_variant_position_index.py
Labels: database
