Repository ccmbioinfo/stager, pull requests merged in 2021-11, with the labels that each got.

#899 React/Flask: Fix participant modal.
  flask/app/families.py
  flask/app/participants.py
  react/src/Datasets/components/DatasetInfoDialog.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/Participants/components/SampleTable.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/components/DetailSection.tsx
  react/src/components/FieldDisplay.tsx
  react/src/components/FieldDisplayEditable.tsx
  react/src/functions.tsx
  react/src/hooks/family/useFamiliesQuery.tsx
  react/src/hooks/family/useFamilyUpdateMutation.tsx
  react/src/hooks/index.tsx
  react/src/typings.tsx
Labels: backend, frontend

#930 React: Modal loading and circular progress icon display.
  docker-compose.test.yaml
  react/src/Datasets/components/DatasetInfoDialog.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/components/LoadingIndicator.tsx
  react/src/components/index.tsx
Labels: frontend, devops

#931 Docker: disable MinIO update check at startup, forward Console port, freeze version
  docker-compose.oidc.yaml
  docker-compose.prod.yaml
  docker-compose.test.yaml
  docker-compose.yaml
Labels: devops

#927 Flask: separate MinIO upload bucket from results bucket
  .github/workflows/flask.yml
  flask/app/groups.py
  flask/app/madmin.py
  flask/app/manage.py
  flask/tests/test_groups.py
Labels: backend, database, devops, tests

#932 React: use no-referrer globally and for all external links
  react/public/index.html
  react/src/AddDatasets/components/DataEntryToolbar.tsx
  react/src/Settings/components/Instructions.tsx
  react/src/Settings/index.tsx
Labels: frontend

#933 VSCode: Use Docker profile to enable debugger functionality in a flask container.
  docker-compose.yaml
  docs/vscode.md
  flask/requirements-dev.in
  flask/requirements-dev.txt
Labels: documentation, backend, dependencies, devops

#938 React: fix dataset types going out of sync between the Dataset and Participant modals
  flask/app/participants.py
  react/src/hooks/datasets/useDatasetUpdateMutation.tsx
  react/src/hooks/participants/useParticipantQuery.tsx
Labels: backend, frontend

#945 Docker: fix up configurations
  docker-compose.cheo.yaml
  docker-compose.oidc.yaml
  docker-compose.prod.yaml
  docker-compose.test.yaml
  docker-compose.yaml
  docs/docker.md
  flask/healthcheck.py
  sample.env
Labels: documentation, backend, devops

#943 React/Flask: Add condition to dataset_type editability, fix Analyses table part I.
  flask/app/analyses.py
  flask/app/datasets.py
  flask/tests/conftest.py
  flask/tests/test_analyses.py
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/components/ExactMatchFilterToggle.tsx
  react/src/functions.tsx
  react/src/hooks/analyses/useAnalysisCreateMutation.tsx
  react/src/hooks/analyses/useAnalysisUpdateMutation.tsx
  react/src/hooks/datasets/useDatasetsPage.tsx
  react/src/typings.tsx
Labels: backend, frontend, tests

#948 Flask: Check for duplicate datasets
  flask/app/routes.py
  flask/tests/test_misc.py
Labels: backend, tests

#946 React: Fix actions in Analysis Table.
  react/src/Analyses/index.tsx
Labels: frontend

#952 Flask: Remove related objects when a dataset is deleted.
  flask/app/datasets.py
  flask/tests/test_datasets.py
Labels: backend, tests

#954 Flask: add MINIO_TLS envvar
  flask/app/buckets.py
  flask/app/config.py
  flask/app/groups.py
  flask/app/utils.py
Labels: backend

#955 Docker: use single-threaded Gunicorn workers scaled to the number of cores
  .github/workflows/flask.yml
  docker-compose.cheo.yaml
  flask/utils/run.sh
Labels: backend, devops

#940 React: Dynamic Endpoint Selection
  react/.gitignore
  react/public/sample.labs.json
  react/src/AddDatasets/components/UploadDialog.tsx
  react/src/App.tsx
  react/src/Login.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/components/LabDropdownSelect.tsx
  react/src/hooks/bulk/useBulkCreateMutation.tsx
  react/src/hooks/utils.tsx
  react/src/typings.tsx
Labels: frontend

#957 React: disable fetch to labs.json
  react/src/App.tsx
Labels: frontend
