Repository ccmbioinfo/stager, pull requests merged in 2021-02, with the labels that each got.

#351 Flask: deny MinIO delete actions
  flask/app/groups.py
  flask/app/madmin.py
  flask/app/manage.py
  flask/tests/test_groups.py
  flask/tests/test_users.py
Labels: backend, database, tests

#352 React: Hookup Participants Page with progressive loading using react-query
  flask/app/participants.py
  flask/tests/test_participants.py
  react/src/Participants/components/ParticipantTable.tsx
  react/src/hooks/index.tsx
  react/src/hooks/participants/useParticipantsPage.tsx
  react/src/hooks/utils.tsx
Labels: backend, frontend, tests

#358 Flask: update start and finish times based on analysis state changes
  flask/app/analyses.py
Labels: backend

#359 React: use /api/metadatasettypes, switch chip bar type
  react/src/AddDatasets/components/utils.tsx
  react/src/Datasets/components/DatasetInfoDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/Participants/components/SampleTable.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/components/DetailSection.tsx
  react/src/components/FieldDisplayEditable.tsx
  react/src/components/GridFieldsDisplay.tsx
  react/src/components/InfoList.tsx
  react/src/hooks/index.tsx
  react/src/hooks/useEnumsQuery.tsx
  react/src/hooks/useMetadatasetTypesQuery.tsx
  react/src/typings.tsx
Labels: frontend

#365 React: Add institution field to participant info dialog
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/hooks/index.tsx
  react/src/hooks/useInstitutionsQuery.tsx
  react/src/typings.tsx
Labels: frontend

#366 Flask: minor db changes
  flask/app/models.py
  flask/migrations/versions/ded8d42ffcb7_change_extraction_protocol_to_freetext_.py
  flask/tests/test_misc.py
Labels: backend, database, tests

#367 React: Use React Context for current authenticated user
  react/src/AddDatasets/index.tsx
  react/src/App.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Datasets/index.tsx
  react/src/Login.tsx
  react/src/Navigation.tsx
  react/src/Settings/index.tsx
  react/src/contexts/index.tsx
  react/src/contexts/useUserContext.tsx
  react/src/typings.tsx
Labels: frontend

#370 React: Add institution column to Add Datasets
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/components/utils.tsx
  react/src/typings.tsx
Labels: frontend

#372 React: fix potentially undefined enum indexing and remove extraction protocol
  react/src/components/FieldDisplayEditable.tsx
Labels: bug, frontend

#373 React: Hookup Add Datasets using react-query
  react/src/AddDatasets/index.tsx
  react/src/hooks/bulk/useBulkCreateMutation.tsx
  react/src/hooks/index.tsx
Labels: frontend

#375 React: Fix groups mutations to only update group list
  react/src/hooks/groups/useGroupCreateMutation.tsx
  react/src/hooks/groups/useGroupDeleteMutation.tsx
  react/src/hooks/groups/useGroupUpdateMutation.tsx
  react/src/hooks/utils.tsx
Labels: frontend

#369 React: Move signout button, add CCM logo
  react/src/Navigation.tsx
  react/src/assets/logo.png
  react/src/components/NotificationPopover.tsx
Labels: frontend

#371 Flask: reduce data overfetch from participants
  flask/app/participants.py
  flask/app/utils.py
Labels: backend

#376 Flask: add global error handler to return json response
  flask/app/__init__.py
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/error_handler.py
  flask/app/families.py
  flask/app/groups.py
  flask/app/participants.py
  flask/app/routes.py
  flask/app/tissue_samples.py
  flask/app/users.py
  flask/app/utils.py
  flask/tests/test_login.py
  flask/tests/test_users.py
Labels: backend, tests

#386 React: Hookup datasets page using react-query
  react/src/Datasets/components/DatasetInfoDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/components/DetailSection.tsx
  react/src/hooks/datasets/useDatasetCreateMutation.tsx
  react/src/hooks/datasets/useDatasetDeleteMutation.tsx
  react/src/hooks/datasets/useDatasetQueries.tsx
  react/src/hooks/datasets/useDatasetQuery.tsx
  react/src/hooks/datasets/useDatasetUpdateMutation.tsx
  react/src/hooks/datasets/useDatasetsPage.tsx
  react/src/hooks/datasets/useDatasetsQuery.tsx
  react/src/hooks/index.tsx
  react/src/hooks/participants/useParticipantsPage.tsx
  react/src/hooks/utils.tsx
  react/src/typings.tsx
Labels: frontend

#399 Docker: lock MinIO to previous version to fix CI failures
  Dockerfile
  docker-compose.prod.yaml
  docker-compose.test.yaml
  docker-compose.yaml
  flask/Dockerfile
Labels: backend, devops

#387 React: Hookup unlinked files with react-query
  flask/app/buckets.py
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/hooks/index.tsx
  react/src/hooks/unlinked/useUnlinkedFilesQuery.tsx
Labels: backend, frontend

#388 Flask: finish implementing progressive loading and filtering on /api/participants
  flask/app/manage.py
  flask/app/models.py
  flask/app/participants.py
  flask/app/utils.py
Labels: backend, database

#403 React: Fix current user groups not being updated in admin
  react/src/AddDatasets/index.tsx
  react/src/App.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Navigation.tsx
  react/src/Settings/index.tsx
  react/src/contexts/index.tsx
  react/src/contexts/useUserContext.tsx
  react/src/hooks/users/useUsersUpdateMutation.tsx
Labels: frontend

#404 React: Hookup /api/pipelines using react-query
  react/src/Datasets/components/AnalysisRunnerDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/hooks/index.tsx
  react/src/hooks/usePipelinesQuery.tsx
Labels: frontend

#407 React: Add tooltips to drawer links when collapsed
  react/src/Navigation.tsx
  react/src/components/ListItemRouterLink.tsx
Labels: frontend

#408 React: Update participants hookup for progressive loading
  react/src/Participants/components/ParticipantTable.tsx
  react/src/hooks/utils.tsx
Labels: frontend

#410 React: Save entered Add Datasets info in sessionStorage
  react/src/AddDatasets/index.tsx
Labels: frontend

#402 docs: info about using GHCR
  Dockerfile
  docs/database.md
  docs/docker.md
  flask/Dockerfile
Labels: backend, documentation

#401 Flask: add formatting to logger and logging to families
  flask/app/__init__.py
  flask/app/families.py
Labels: backend

#389 Flask: implement progressive loading and filtering on /api/datasets
  flask/app/datasets.py
  flask/app/models.py
  flask/app/participants.py
  flask/app/utils.py
  flask/tests/test_datasets.py
Labels: backend, database, tests

#400 React: Hookup analyses page with react-query
  react/src/Analyses/index.tsx
  react/src/Datasets/components/AnalysisRunnerDialog.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/components/NotificationPopover.tsx
  react/src/hooks/analyses/useAnalysesPage.tsx
  react/src/hooks/analyses/useAnalysesQuery.tsx
  react/src/hooks/analyses/useAnalysisCreateMutation.tsx
  react/src/hooks/analyses/useAnalysisDeleteMutation.tsx
  react/src/hooks/analyses/useAnalysisQuery.tsx
  react/src/hooks/analyses/useAnalysisUpdateMutation.tsx
  react/src/hooks/index.tsx
  react/src/typings.tsx
Labels: frontend

#418 Flask: add logging to endpoints in routes
  flask/app/routes.py
Labels: backend

#420 Flask: add logging to tissue sample endpoints
  flask/app/tissue_samples.py
Labels: backend
