Repository ccmbioinfo/stager, pull requests merged in 2021-04, with the labels that each got.

#478 use tableRef to update dataset type filter on dataset page
  react/src/Datasets/components/DatasetTable.tsx
Labels: frontend

#454 Docker: remove wrapper script for prod image, reorganize database seeds to separate dev data
  Dockerfile
  docker-compose.prod.yaml
  docker-compose.test.yaml
  docker-compose.yaml
  flask/Dockerfile
  flask/app/__init__.py
  flask/app/manage.py
  flask/tests/test_groups.py
  flask/tests/test_madmin.py
  flask/utils/run.sh
  nginx/conf.d/default.conf
Labels: backend, database, devops, tests

#493 Cklamann/material table fixes
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/functions.tsx
Labels: frontend

#484 Flask: add validate_json decorator to replace request.json checks
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/families.py
  flask/app/groups.py
  flask/app/participants.py
  flask/app/routes.py
  flask/app/tissue_samples.py
  flask/app/users.py
  flask/app/utils.py
  flask/tests/conftest.py
  flask/tests/test_datasets.py
  flask/tests/test_samples.py
  flask/tests/test_users.py
  flask/tests/test_validation.py
  react/src/App.tsx
  react/src/hooks/users/useUserMinioMutation.tsx
Labels: backend, frontend, tests

#490 React: limit notification list to 50 most recent
  react/src/components/NotificationPopover.tsx
  react/src/hooks/analyses/useAnalysesQuery.tsx
  react/src/hooks/utils.tsx
Labels: frontend

#463 Flask: schema changes to gene pull viewer
  flask/app/models.py
  flask/migrations/versions/12eef79e0a33_gene_viewer_schema.py
  flask/migrations/versions/2a2bc309568d_initial_migration.py
  flask/migrations/versions/ded8d42ffcb7_change_extraction_protocol_to_freetext_.py
  flask/tests/test_misc.py
Labels: backend, database, tests

#495 Flask: pip-compile --upgrade
  flask/requirements-dev.txt
  flask/requirements.txt
Labels: backend, dependencies

#501 db: seed dig2 pipeline for RRS, add separate group seed command without dummy users
  flask/app/manage.py
Labels: database

#500 Flask: add GET variant summary endpoint
  flask/app/__init__.py
  flask/app/gene_viewer.py
Labels: backend

#506 Flask: /api/groups fix-up related to CodeQL warning
  flask/app/groups.py
  flask/tests/test_groups.py
Labels: backend, tests

#502 Create gene search autocomplete component and summary gene endpoints
  flask/app/__init__.py
  flask/app/genes.py
  flask/tests/test_genes.py
  react/src/Navigation.tsx
  react/src/SearchVariants/components/Autocomplete.tsx
  react/src/SearchVariants/components/SearchVariantsPage.tsx
  react/src/SearchVariants/index.tsx
  react/src/hooks/genes/index.ts
  react/src/hooks/genes/useGenesQuery.ts
  react/src/hooks/utils.tsx
  react/src/hooks/variants/index.ts
  react/src/hooks/variants/useVariantsQuery.ts
  react/src/typings.tsx
Labels: backend, frontend, tests

#508 Flask: add test data and tests for variant summary
  flask/tests/conftest.py
  flask/tests/test_datasets.py
  flask/tests/test_families.py
  flask/tests/test_genes.py
  flask/tests/test_participants.py
  flask/tests/test_samples.py
  flask/tests/test_variants.py
Labels: backend, tests

#509 Flask: /api/users fix-up related to CodeQL warning
  flask/app/groups.py
  flask/app/users.py
  flask/app/utils.py
  flask/tests/test_users.py
Labels: backend, tests

#520 Flask: add priority column to analysis table
  flask/app/models.py
  flask/migrations/versions/2a2bc309568d_initial_migration.py
  flask/tests/test_misc.py
Labels: backend, database, tests

#511 CI: build frontend for both CCM and CHEO-RI targets on master only
  .github/workflows/react.yml
Labels: devops

#521 Flask: minor bug fixes to /api/datasets
  flask/app/datasets.py
Labels: backend, bug

#510 React: CSV template download in Add Datasets
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/components/UploadCSV.tsx
  react/src/AddDatasets/components/UploadDialog.tsx
  react/src/AddDatasets/components/utils.tsx
Labels: frontend

#518 connect autocomplete to variant csv endpoint
  react/src/SearchVariants/components/Autocomplete.tsx
  react/src/SearchVariants/components/SearchVariantsPage.tsx
  react/src/hooks/utils.tsx
  react/src/hooks/variants/useVariantsQuery.ts
Labels: frontend

#522 Add analysis priority flag to fe components and process attribute in backend routes
  flask/app/analyses.py
  flask/app/utils.py
  flask/tests/test_analyses.py
  react/src/Analyses/index.tsx
  react/src/Datasets/components/AnalysisRunnerDialog.tsx
  react/src/hooks/analyses/useAnalysisCreateMutation.tsx
  react/src/hooks/analyses/useAnalysisUpdateMutation.tsx
  react/src/typings.tsx
Labels: backend, frontend, tests

#523 Flask: accept trailing slashes for endpoints with children
  flask/app/datasets.py
  flask/app/families.py
  flask/app/groups.py
  flask/app/participants.py
  flask/app/routes.py
  flask/app/tissue_samples.py
  flask/app/users.py
Labels: backend

#524 React: support larger page sizes and retrieving all rows
  react/src/Analyses/components/DatasetTable.tsx
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/components/MaterialTablePaginationOverride.tsx
  react/src/components/MaterialTablePrimary.tsx
  react/src/components/index.tsx
  react/src/hooks/utils.tsx
Labels: frontend

#536 Flask: Fix setting assignee for analysis
  flask/app/analyses.py
Labels: backend, bug

#525 Flask: GET /api/summary/participants
  flask/app/__init__.py
  flask/app/gene_viewer.py
  flask/app/variants.py
  flask/tests/test_variants.py
Labels: backend, tests

#537 CI: login to registry with GITHUB_TOKEN
  .github/workflows/flask.yml
Labels: devops

#539 React: apply new ESLint rules
  flask/.gitignore
  react/package.json
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/components/TableCells.tsx
  react/src/AddDatasets/components/UploadCSV.tsx
  react/src/AddDatasets/components/UploadDialog.tsx
  react/src/AddDatasets/components/utils.tsx
  react/src/AddDatasets/index.tsx
  react/src/Admin/components/CreateUserModal.tsx
  react/src/Admin/components/GroupSelect.tsx
  react/src/Admin/components/UserDetails.tsx
  react/src/Admin/components/UserList.tsx
  react/src/Admin/components/UserRow.tsx
  react/src/Admin/index.tsx
  react/src/Analyses/components/ChipStrip.tsx
  react/src/Analyses/components/PipelineFilter.tsx
  react/src/Analyses/index.tsx
  react/src/App.tsx
  react/src/Datasets/components/AnalysisRunnerDialog.tsx
  react/src/Datasets/components/DatasetInfoDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Datasets/components/LinkedFilesButton.tsx
  react/src/Datasets/index.tsx
  react/src/Groups/components/CreateGroupModal.tsx
  react/src/Groups/components/Group.tsx
  react/src/Groups/index.tsx
  react/src/Login.tsx
  react/src/Navigation.tsx
  react/src/Participants/components/DatasetTypes.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/Participants/components/SampleTable.tsx
  react/src/Participants/index.tsx
  react/src/SearchVariants/components/Autocomplete.tsx
  react/src/SearchVariants/components/SearchVariantsPage.tsx
  react/src/Settings/index.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/components/Card.tsx
  react/src/components/DateFilterComponent.tsx
  react/src/components/DetailSection.tsx
  react/src/components/FieldDisplay.tsx
  react/src/components/FieldDisplayEditable.tsx
  react/src/components/FileLinkingComponent.tsx
  react/src/components/GroupDropdownSelect.tsx
  react/src/components/InfoList.tsx
  react/src/components/ListItemRouterLink.tsx
  react/src/components/MinioResetButton.tsx
  react/src/components/NewPasswordForm.tsx
  react/src/components/Notification.tsx
  react/src/components/NotificationPopover.tsx
  react/src/functions.tsx
  react/src/hooks/analyses/useAnalysesPage.tsx
  react/src/hooks/groups/useGroupUpdateMutation.tsx
  react/src/hooks/participants/useParticipantsPage.tsx
  react/src/hooks/users/useUsersCreateMutation.tsx
  react/src/hooks/utils.tsx
  react/yarn.lock
Labels: dependencies, frontend

#551 CI: fix stale yarn caches from always using the same key
  .github/workflows/react.yml
Labels: bug, devops

#526 React: Add row-based editing for assignee, status on Analysis table
  react/src/Analyses/components/CancelAnalysisDialog.tsx
  react/src/Analyses/components/SelectPipelineStatus.tsx
  react/src/Analyses/components/SetAssigneeDialog.tsx
  react/src/Analyses/index.tsx
  react/src/App.tsx
  react/src/components/SelectFilterComponent.tsx
  react/src/functions.tsx
  react/src/hooks/analyses/useAnalysisCreateMutation.tsx
  react/src/hooks/analyses/useAnalysisDeleteMutation.tsx
  react/src/hooks/analyses/useAnalysisUpdateMutation.tsx
  react/src/hooks/utils.tsx
Labels: frontend

#538 React: add catch-all route for 404s
  react/src/Navigation.tsx
  react/src/NotFound/index.tsx
Labels: frontend

#540 React: small tweaks to column order, remove analysis chip buttons
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/components/MaterialTablePrimary.tsx
Labels: frontend

#552 React: Add progressive loading to Add Datasets suggestions
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/components/DataEntryTableRow.tsx
  react/src/AddDatasets/components/DataEntryToolbar.tsx
  react/src/AddDatasets/components/TableCells.tsx
  react/src/hooks/useFamiliesQuery.tsx
Labels: frontend
