Repository ccmbioinfo/stager, pull requests merged in 2021-05, with the labels that each got.

#562 React: display sequencing_date as Report Date
  react/package.json
  react/src/AddDatasets/components/utils.tsx
  react/yarn.lock
Labels: dependencies, frontend

#563 React: Fix text wrapping inside info dialogs
  react/src/components/GridFieldsDisplay.tsx
Labels: bug, frontend

#507 Epic: OAuth authentication support
  docker-compose.oidc.yaml
  docker-compose.test.yaml
  docker-compose.yaml
  docs/oidc.md
  flask/app/__init__.py
  flask/app/config.py
  flask/app/extensions.py
  flask/app/manage.py
  flask/app/manage_keycloak.py
  flask/app/models.py
  flask/app/routes.py
  flask/app/utils.py
  flask/migrations/versions/42a60aeca550_add_oidc_fields_to_user.py
  flask/requirements-dev.txt
  flask/requirements.in
  flask/requirements.txt
  init/01-database.sh
  react/sample.env
  react/src/App.tsx
  react/src/Login.tsx
  sample.env
Labels: backend, database, dependencies, devops, documentation, frontend

#566 React: add MinIO usage instructions to Settings
  react/src/Settings/components/Instructions.tsx
  react/src/Settings/index.tsx
Labels: frontend

#567 Epic: Export all Data from Tables
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/genes.py
  flask/app/participants.py
  flask/app/utils.py
  flask/app/variants.py
  flask/tests/test_genes.py
  flask/tests/unit/test_json_validation_decorator.py
  flask/tests/unit/test_query_results_to_csv.py
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/SearchVariants/components/SearchVariantsPage.tsx
  react/src/components/EditNotes.tsx
  react/src/components/index.tsx
  react/src/functions.tsx
  react/src/hooks/analyses/useAnalysesPage.tsx
  react/src/hooks/datasets/useDatasetsPage.tsx
  react/src/hooks/index.tsx
  react/src/hooks/participants/useParticipantsPage.tsx
  react/src/hooks/useDownloadCsv.ts
  react/src/hooks/utils.tsx
  react/src/hooks/variants/index.ts
  react/src/hooks/variants/useVariantsQuery.ts
  react/src/typings.tsx
Labels: backend, frontend, tests

#569 React: Update participant info dialog content and formatting
  flask/app/datasets.py
  react/src/Analyses/index.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/Participants/components/SampleTable.tsx
  react/src/components/DateTimeText.tsx
  react/src/components/DetailSection.tsx
  react/src/components/FieldDisplayEditable.tsx
  react/src/components/GridFieldsDisplay.tsx
  react/src/functions.tsx
  react/src/typings.tsx
Labels: backend, frontend

#586 Flask: Replace pipeline_id column with analysis_state column in analyses csv export
  flask/app/analyses.py
  flask/tests/test_madmin.py
Labels: backend, tests

#579 React: updates to Add Datasets
  flask/app/routes.py
  react/src/AddDatasets/components/TableCells.tsx
  react/src/AddDatasets/components/utils.tsx
  react/src/AddDatasets/index.tsx
  react/src/SearchVariants/components/Autocomplete.tsx
Labels: backend, frontend

#587 React: Save default table filters to localStorage
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/hooks/index.tsx
  react/src/hooks/useTableFilterCache.tsx
Labels: frontend

#588 React: Save hidden column states to localStorage
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/hooks/index.tsx
  react/src/hooks/useHiddenColumnCache.tsx
Labels: frontend

#589 React: Update custom material-table filters to be controlled components
  react/src/Analyses/components/PipelineFilter.tsx
  react/src/components/BooleanFilter.tsx
  react/src/components/DateFilterComponent.tsx
Labels: frontend

#591 Docker: fix nginx resolving to stale DNS entries when containers are replaced
  nginx/conf.d/default.conf
Labels: devops

#590 React/Flask: Change default ordering for tables
  flask/app/analyses.py
  flask/app/participants.py
  react/src/Analyses/index.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/hooks/useSortOrderCache.tsx
Labels: backend, frontend

#592 React & Flask: Add permission group column to datasets
  flask/app/datasets.py
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/components/ChipGroup.tsx
  react/src/typings.tsx
Labels: backend, frontend

#607 Flask: fix directories being listed instead of files
  flask/app/buckets.py
  react/yarn.lock
Labels: backend, bug, dependencies, frontend

#601 React: Update dialogs for missing info
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/participants.py
  react/src/Datasets/components/DatasetInfoDialog.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/components/DetailSection.tsx
  react/src/components/FieldDisplayEditable.tsx
  react/src/functions.tsx
  react/src/typings.tsx
Labels: backend, frontend

#610 CI: add REACT_APP_EMAIL to builds
  .github/workflows/react.yml
Labels: devops

#602 Flask: Add POST /api/analyses/:id for simple re-analysis
  flask/app/analyses.py
  flask/app/utils.py
  flask/tests/test_analyses.py
  react/src/Datasets/components/AnalysisRunnerDialog.tsx
  react/src/hooks/analyses/useAnalysisCreateMutation.tsx
Labels: backend, frontend, tests

#568 Flask: support gene aliases, use Ensembl IDs as gene primary key
  flask/app/extensions.py
  flask/app/genes.py
  flask/app/models.py
  flask/app/variants.py
  flask/migrations/versions/5e69ca582792_genes_by_position.py
  flask/tests/conftest.py
  flask/tests/test_genes.py
  flask/tests/test_variants.py
Labels: backend, database, tests

#616 Flask: bump from 1.1.2 to 2.0.1, drop unused flask_wtf
  flask/app/utils.py
  flask/requirements-dev.txt
  flask/requirements.in
  flask/requirements.txt
Labels: backend, dependencies

#618 React: Fix pipeline filter not being updated properly
  react/src/Analyses/components/PipelineFilter.tsx
Labels: bug, frontend

#605 React: Add reanalysis button to analysis info dialog
  react/src/Datasets/components/AnalysisRunnerDialog.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/hooks/analyses/useAnalysisCreateMutation.tsx
Labels: frontend

#624 React: update variant viewer frontend to match #568
  flask/app/variants.py
  react/src/SearchVariants/components/Autocomplete.tsx
  react/src/SearchVariants/components/SearchVariantsPage.tsx
  react/src/hooks/genes/useGenesQuery.ts
  react/src/typings.tsx
Labels: backend, frontend

#623 React: Add OAuth fields to Admin Page
  react/src/Admin/components/CreateUserModal.tsx
  react/src/Admin/components/UserDetails.tsx
  react/src/App.tsx
  react/src/contexts/index.tsx
  react/src/contexts/useOAuthContext.tsx
  react/src/typings.tsx
Labels: frontend

#622 React/Flask: Add fields to analyses table and introduce multifield search
  flask/app/analyses.py
  flask/tests/test_analyses.py
  react/src/Analyses/index.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/hooks/analyses/useAnalysesPage.tsx
  react/src/hooks/utils.tsx
  react/src/typings.tsx
Labels: backend, frontend, tests

#620 Flask: Update user endpoints to support OIDC fields
  flask/app/users.py
Labels: backend
