Repository ccmbioinfo/stager, pull requests merged in 2022-01, with the labels that each got.

#951 Add Locust for load testing
  docs/locust.md
  locust/.gitignore
  locust/launch.py
  locust/locustfile.py
  locust/requirements.in
  locust/requirements.txt
  locust/sample.env
Labels: documentation

#1008 CI: remove Dependabot assignee
  .github/dependabot.yml
Labels: devops

#1005 Docker: switch to Traefik for multitenant deployment
  .gitignore
  docker-compose.ccm.yaml
  nginx/conf.d/default.conf
  traefik/frontend.yml
  traefik/https.yml
Labels: devops

#1011 CI: fix caching behaviour for frontend workflow
  .github/workflows/react.yml
Labels: devops

#1014 Flask: fix /api/unlinked to allow for prefix searches
  flask/app/buckets.py
Labels: backend

#1012 Flask: fix admins not having MinIO delete permissions
  flask/app/madmin.py
Labels: bug, backend

#1017 CI: deploy Aleixo Muise lab tenant
  .github/workflows/flask.yml
  docker-compose.ccm.yaml
Labels: devops

#1010 React: Handle NetworkError and raised exceptions.
  react/src/AddDatasets/components/UploadDialog.tsx
  react/src/AddDatasets/index.tsx
  react/src/Admin/components/CreateUserModal.tsx
  react/src/App.tsx
  react/src/Groups/index.tsx
  react/src/Login.tsx
  react/src/Navigation.tsx
  react/src/Settings/index.tsx
  react/src/hooks/analyses/useAnalysesQuery.tsx
  react/src/hooks/analyses/useAnalysisQuery.tsx
  react/src/hooks/datasets/useDatasetQueries.tsx
  react/src/hooks/datasets/useDatasetQuery.tsx
  react/src/hooks/datasets/useDatasetsQuery.tsx
  react/src/hooks/family/useFamiliesQuery.tsx
  react/src/hooks/genes/useGenesQuery.ts
  react/src/hooks/groups/useGroupsQuery.tsx
  react/src/hooks/index.tsx
  react/src/hooks/participants/useParticipantQuery.tsx
  react/src/hooks/useDownloadCsv.ts
  react/src/hooks/useInstitutionsQuery.tsx
  react/src/hooks/useMetadatasetTypesQuery.tsx
  react/src/hooks/usePipelinesQuery.tsx
  react/src/hooks/users/useUserQuery.tsx
  react/src/hooks/users/useUsersQuery.tsx
  react/src/hooks/utils.tsx
Labels: frontend

#1018 Revert "React: improve AJAX error handling (#1010)"
  react/src/AddDatasets/components/UploadDialog.tsx
  react/src/AddDatasets/index.tsx
  react/src/Admin/components/CreateUserModal.tsx
  react/src/App.tsx
  react/src/Groups/index.tsx
  react/src/Login.tsx
  react/src/Navigation.tsx
  react/src/Settings/index.tsx
  react/src/hooks/analyses/useAnalysesQuery.tsx
  react/src/hooks/analyses/useAnalysisQuery.tsx
  react/src/hooks/datasets/useDatasetQueries.tsx
  react/src/hooks/datasets/useDatasetQuery.tsx
  react/src/hooks/datasets/useDatasetsQuery.tsx
  react/src/hooks/family/useFamiliesQuery.tsx
  react/src/hooks/genes/useGenesQuery.ts
  react/src/hooks/groups/useGroupsQuery.tsx
  react/src/hooks/index.tsx
  react/src/hooks/participants/useParticipantQuery.tsx
  react/src/hooks/useDownloadCsv.ts
  react/src/hooks/useInstitutionsQuery.tsx
  react/src/hooks/useMetadatasetTypesQuery.tsx
  react/src/hooks/usePipelinesQuery.tsx
  react/src/hooks/users/useUserQuery.tsx
  react/src/hooks/users/useUsersQuery.tsx
  react/src/hooks/utils.tsx
Labels: frontend

#1019 React: Improve AJAX error handling
  react/src/AddDatasets/components/UploadDialog.tsx
  react/src/AddDatasets/index.tsx
  react/src/Admin/components/CreateUserModal.tsx
  react/src/App.tsx
  react/src/Groups/index.tsx
  react/src/Login.tsx
  react/src/Navigation.tsx
  react/src/Settings/index.tsx
  react/src/hooks/analyses/useAnalysesQuery.tsx
  react/src/hooks/analyses/useAnalysisQuery.tsx
  react/src/hooks/datasets/useDatasetQueries.tsx
  react/src/hooks/datasets/useDatasetQuery.tsx
  react/src/hooks/datasets/useDatasetsQuery.tsx
  react/src/hooks/family/useFamiliesQuery.tsx
  react/src/hooks/genes/useGenesQuery.ts
  react/src/hooks/groups/useGroupsQuery.tsx
  react/src/hooks/index.tsx
  react/src/hooks/participants/useParticipantQuery.tsx
  react/src/hooks/useDownloadCsv.ts
  react/src/hooks/useInstitutionsQuery.tsx
  react/src/hooks/useMetadatasetTypesQuery.tsx
  react/src/hooks/usePipelinesQuery.tsx
  react/src/hooks/users/useUserQuery.tsx
  react/src/hooks/users/useUsersQuery.tsx
  react/src/hooks/utils.tsx
Labels: frontend

#1020 CI: Use pytest-cov to measure code coverage
  .github/workflows/flask.yml
  README.md
  docs/flask.md
  flask/.dockerignore
  flask/.gitignore
  flask/requirements-dev.in
  flask/requirements-dev.txt
Labels: documentation, backend, dependencies, devops

#1016 Flask: Input validation for _bulk, create_user and create_group endpoints
  flask/app/analyses.py
  flask/app/config.py
  flask/app/datasets.py
  flask/app/families.py
  flask/app/groups.py
  flask/app/madmin.py
  flask/app/participants.py
  flask/app/routes.py
  flask/app/schemas.py
  flask/app/tissue_samples.py
  flask/app/users.py
  flask/app/utils.py
  flask/tests/test_groups.py
  flask/tests/test_misc.py
Labels: backend, tests

#1028 Flask: upgrade to Python 3.8
  Dockerfile
  flask/Dockerfile
  flask/tests/test_misc.py
  flask/tests/unit/test_json_validation_decorator.py
Labels: backend, tests

#1026 React: fix security warnings
  react/yarn.lock
Labels: frontend, dependencies

#1027 Flask: make most initializations of MinIO client SDKs consistent
  flask/app/manage.py
Labels: bug, database
