Repository ccmbioinfo/stager, pull requests merged in 2022-04, with the labels that each got.

#1108 React: Fix the bug in dataset modal to get options for Dataset types
  react/src/components/FieldDisplayEditable.tsx
Labels: frontend

#1112 React: Display human-readable names for dataset types
  react/src/AddDatasets/components/TableCells.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/components/FieldDisplay.tsx
  react/src/components/TooltipDatasetType.tsx
  react/src/components/index.tsx
Labels: frontend

#1116 React: package upgrade
  react/package.json
  react/yarn.lock
Labels: frontend, dependencies

#1123 React: package upgrade again - Dependabot security warnings
  react/package.json
  react/yarn.lock
Labels: frontend, dependencies

#1122 React: fix candidate genes dropdown
  react/src/components/AutocompleteMultiselect.tsx
Labels: bug, frontend

#1117 Flask: package upgrade
  flask/requirements-dev.txt
  flask/requirements.txt
Labels: backend, dependencies
