Repository ccmbioinfo/stager, pull requests merged in 2022-03, with the labels that each got.

#1068 React: Expose button to delete analysis on the front-end
  react/src/Analyses/index.tsx
Labels: frontend

#1049 CI: add backend rollback workflow
  .github/workflows/flask-rollback.yml
Labels: devops

#1076 Flask: Fix Marshmallow validation error logging
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/families.py
  flask/app/groups.py
  flask/app/participants.py
  flask/app/routes.py
  flask/app/tissue_samples.py
  flask/app/users.py
Labels: bug, backend

#1073 Flask/React: clean-up for pipeline automation
  flask/app/analyses.py
  flask/app/datasets.py
  flask/app/manage.py
  flask/app/models.py
  flask/app/routes.py
  flask/app/schemas.py
  flask/app/slurm.py
  flask/app/tasks.py
  flask/migrations/versions/83abd5d883b6_add_vcf_available_and_candidate_genes_.py
  flask/migrations/versions/c137bdb34421_convert_metadataset_types_and_pipelines_.py
  flask/tests/conftest.py
  flask/tests/test_analyses.py
  flask/tests/test_misc.py
  react/src/AddDatasets/components/DataEntryTable.tsx
  react/src/AddDatasets/components/utils.tsx
  react/src/Analyses/components/PipelineFilter.tsx
  react/src/Analyses/index.tsx
  react/src/App.tsx
  react/src/Datasets/components/AnalysisRunnerDialog.tsx
  react/src/Datasets/components/DatasetInfoDialog.tsx
  react/src/Datasets/components/DatasetTable.tsx
  react/src/Participants/components/ParticipantInfoDialog.tsx
  react/src/Participants/components/ParticipantTable.tsx
  react/src/Participants/components/SampleTable.tsx
  react/src/components/AnalysisInfoDialog.tsx
  react/src/components/DetailSection.tsx
  react/src/components/FieldDisplayEditable.tsx
  react/src/components/GridFieldsDisplay.tsx
  react/src/components/InfoList.tsx
  react/src/hooks/analyses/useAnalysisCreateMutation.tsx
  react/src/hooks/index.tsx
  react/src/hooks/useEnumsQuery.tsx
  react/src/hooks/useMetadatasetTypesQuery.tsx
  react/src/hooks/usePipelinesQuery.tsx
  react/src/typings.tsx
Labels: backend, frontend, database, tests

#1077 Flask: add new dataset types
  flask/app/models.py
Labels: database

#1078 Flask: divert SQLAlchemy logs to sidecar in production
  docker-compose.ccm.yaml
  docker-compose.cheo.yaml
  docker-compose.yaml
  docs/production.md
  flask/app/__init__.py
Labels: documentation, backend, devops

#1080 CI: add workflow to validate Docker Compose files
  .github/workflows/compose-validate.yml
  docker-compose.ccm.yaml
Labels: devops

#1084 CI: use actions/setup-node to cache yarn dependencies
  .github/workflows/react.yml
Labels: devops
