Repository ccmbioinfo/stager, pull requests merged in 2022-02, with the labels that each got.

#1042 Flask: Upgrade to python 3.8 (again)
  Dockerfile
  flask/Dockerfile
  flask/app/schemas.py
  flask/tests/test_misc.py
  flask/tests/unit/test_json_validation_decorator.py
Labels: backend, tests

#1041 Flask: fix mc mirror --watch failing with Access Denied
  flask/app/madmin.py
Labels: bug, backend

#1032 Flask: make most initializations of MinIO client SDKs consistent
  flask/app/manage.py
Labels: database

#1046 Flask: Upgrade from Python 3.8 to Python 3.9
  Dockerfile
  README.md
  docs/docker.md
  docs/flask.md
  docs/locust.md
  flask/Dockerfile
Labels: documentation, backend

#1047 Traefik: switch internal API, metrics to HTTPS/8443, enable HSTS
  docker-compose.ccm.yaml
  docs/production.md
  traefik/frontend.yml
  traefik/https.yml
  traefik/traefik-api.yml
Labels: documentation, devops

#1048 CI: automatically cancel outdated jobs
  .github/workflows/codeql-analysis.yml
  .github/workflows/flask.yml
  .github/workflows/react.yml
Labels: devops

#1029 Flask: made unlinked file query non-recursive to reduce payload
  flask/app/buckets.py
  react/src/components/AutocompleteMultiselect.tsx
  react/src/hooks/unlinked/useUnlinkedFilesQuery.tsx
Labels: backend, frontend
